version: '3'
services: 
  mysql-mystore:
    build:
      dockerfile: ./mysql.dockerfile
      context: .
    image: andrepapaz/mysql-mystore
    container_name: mysql-mystore
    ports: 
      - "3306"
    networks: 
      - production-network

  spring-app:
    build:
      dockerfile: ./spring.dockerfile
      context: .
    image: andrepapaz/springboot-mystore
    container_name: spring-app
    ports: 
      - "8080:8080"
    networks: 
      - production-network
    depends_on: 
      - "mysql-mystore"

networks: 
  production-network:
    driver: bridge